services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    environment:
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - data-pipeline-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - data-pipeline-network

volumes:
  postgres_data:

networks:
  data-pipeline-network:
    driver: bridge